### ISSUE TITLE
关于源码的几个问题

### ISSUE THREAD

**Issue by rexdf** [yufengzjj/PoCUltraISOKeyGen#1]
我是用的CUDA8.0，VS2015(没装Intel Compiler)，因为发现你的gmp库里面有BMI2指令mulx，这是一条Haswell的指令，我的CPU不支持这条指令。所以我重新用VS编译了gmp等库。

虽然我自己的编译版本算出来的都是错误的注册码，但是发现如果算出一个注册码之后如果继续跑，从第二个开始，不是位数对不上，就是出现乱码符号如下：
```
REGISTRATION CODE:4aa9d2ef8f5b5634
REGISTRATION CODE:dddb265f4a8b442
REGISTRATION CODE:1494e68e961ca6c2€
REGISTRATION CODE:712a1887a8c1ca4a€
```

1.对于那个gmp库的几个问题。
1)mpz_get_str(reinterpret_cast<char *>(&msg[len]), 16, m);如何返回大写的？
我算出了很多都是小写的。
根据 https://gmplib.org/manual/Converting-Integers.html 这个上面的说法，16应该返回小写才对。是不是你在gmp库上面做过什么特殊修改？

2.校验器的问题
1)校验器我也是完全用VS编译了opensll以及源码，校验52pojie上的注册码是正确的。而我自己算出来的10多组全部不对。
2)貌似著名的王姓中文注册码校验对不上。不知道是不是编码方面的问题。

3.代码修改的部分
除了修改gmp的头文件，链接库。还修改了如下的几个地方。不修改，貌似编译通不过。
第一处是std::chrono::system_clock::time_poin与std::chrono::steady_clock::time_point类型不同不能相减。不知道有没有利用这里的某些未定义行为。

第二处修改是unsigned自动转换为int会被vs2015认为是narrowing conversion，直接编译报错。我把int的几个定义都改为unsigned了。不知道源代码是否利用了这里的，unsigned转int的溢出处理的未定义行为？

```
--- a/PoCUtraISOKeyGen/TimeProbe.cpp
+++ b/PoCUtraISOKeyGen/TimeProbe.cpp
@@ -25,7 +25,7 @@ void TimeProbe::tick_start(std::string probe_name)
 void TimeProbe::tick_stop(std::string probe_name)
 {
     m_mtx.lock();
-    std::chrono::system_clock::time_point t = std::chrono::system_clock::now();
+    std::chrono::steady_clock::time_point t = std::chrono::steady_clock::now();
     if (m_ticker.find(probe_name) != m_ticker.end())
     {
         if (std::get<3>(m_ticker[probe_name]) == Status::started)
--- a/PoCUtraISOKeyGen/Helper.cpp
+++ b/PoCUtraISOKeyGen/Helper.cpp
@@ -1,9 +1,9 @@
 #include "Helper.h"
 
 
-Helper::factor Helper::factoring(int num, int max_factor_b)
+Helper::factor Helper::factoring(unsigned num, unsigned max_factor_b)
 {
-    int factor_a = 1, factor_b = 1;
+    unsigned factor_a = 1, factor_b = 1;
     while (factor_a * factor_b != num)
     {
         if (num%factor_a != 0)
diff --git a/PoCUtraISOKeyGen/Helper.h b/PoCUtraISOKeyGen/Helper.h
index 3d070d0..dafd2eb 100644
--- a/PoCUtraISOKeyGen/Helper.h
+++ b/PoCUtraISOKeyGen/Helper.h
@@ -4,15 +4,15 @@ class Helper
 public:
     struct factor
     {
-        int a;
-        int b;
+        unsigned a;
+        unsigned b;
     };
 
     /*
     * always return the minimum factor_a and the maximum under
     * max_factor_b.
     * */
-    static factor factoring(int num, int max_factor_b);
+    static factor factoring(unsigned num, unsigned max_factor_b);
     Helper();
     ~Helper();
 };
```

4.关于那些常数
好多奇怪的常数啊，有几页那么多啊，怎么生成的…… 只是吐槽下

**Comment by HMBSbige** [comment]
我只能回答关于注册码校验问题，
ultraiso有国际版和中文版两种，这款注册机只能通过国际版的，也许是编码问题。
顺便说一下，之前我用vs2015被各种编译报错弄哭，换了2013的就好了。
我本来是打算改进算法加个GPU多线程的，不知道行不行，而且我实在是抽不出时间......
注：我就是那个52pojie算出注册码的那位ヾ(･ω･`｡)

**Comment by rexdf** [comment]
@HMBSbige  我是参考 https://github.com/ShiftMediaProject 这个项目。 这个项目是编译ffmpeg的 http://www.jianshu.com/p/e72e6dce7f23 。但是这个编译过程中产生的附带品是有VS项目编译各种库，如openssl，gmp等48个额外个依赖库。

所以可以直接连接上用这个项目生产的lib，所以编译器链接上就不会出问题了。

**Comment by yufengzjj** [comment]
1.注册算法中都是对大写字母进行计算,所以GMP的库是我修改过的,直接返回大写字符串.小写算出来的是错误的.乱码符号其实没有影响,只是我在获取计算出的数据之后没把最后一个字节写为0.
2.至于中文,貌似@HMBSbige算出来过中文的...具体不清楚,毕竟我没有真正的测试.
3.TimeProbe是测试时候的计时工具,不会有影响.Helper里面factoring辅助在猜解reg code的时候给不同性能GPU分配任务用的,我想也不会有影响,至少int不会有溢出的情况.
4.常数都是从软件里面拿出来的,code计算结果符合常数限制才是正确的.

**Comment by rexdf** [comment]
算出不对的值的原因是因为 `kernel.cpp` `KGCPU.cpp` `KGCUDA.cpp` 这三个文件都`#include "third_party\gmp-6.0.0\gmp.h"`而我只改一个include到自己编译的6.1.1。三个都改一下就是都是正确的了。

挺好的学习材料，感谢！
